spring:
  profiles:
    active: dev
  # 应用配置
  application:
    group: MACULA
    name: macula-samples-bus2
  cloud:
    bus:
      id: ${spring.application.group}:${spring.application.name}:${random.value}
    stream:
      rocketmq:
        binder:
          name-server: ${macula.rocketmq.url}
server:
  port: 8087

macula:
  datasource:
    druid:
      - name: macula-samples
        ## JDBC配置
        url: ${macula.datasource.macula-samples.url}
        username: ${macula.datasource.macula-samples.username}
        password: ${macula.datasource.macula-samples.password}
        ## 连接池配置
        max-active: 100
        initial-size: 1
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: select '1'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 50
        max-pool-prepared-statement-per-connection-size: 20
        ## 过滤器配置
        filters: stat,wall
  jpa:
    repositories:
      - name: macula-samples
        entity-packages: org.macula.samples
        repository-packages: org.macula.samples
        service-package: org.macula.samples

---
spring:
  profiles: dev

macula:
  datasource:
    macula-samples:
      url: jdbc:mysql://127.0.0.1:3306/macula-samples?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
      username: root
      password:
  rocketmq:
    url: 192.168.1.44:9876